[sdl]
fullscreen=false
autolock=false

[dosbox]
machine=svga_s3

[cpu]
core=normal
cycles=12000

[ne2000]
ne2000=true
nicbase=300
nicirq=10
macaddr=AC:DE:48:44:4D:02
backend=slirp

[ethernet, slirp]
restricted=false
disable_host_loopback=false
ipv4_network=10.0.2.0
ipv4_netmask=255.255.255.0
ipv4_host=10.0.2.2
ipv4_nameserver=10.0.2.3
ipv4_dhcp_start=10.0.2.15
udp_port_forwards=21300

[autoexec]
mount c .
c:
PROTOCHK > PROTO.LOG
if not exist C:\REMOTE md C:\REMOTE
NE2000 0x60 10 0x300
RA-TSR pass:dosbox-test 10.0.2.15 21300 0x60 C:\REMOTE RW DOSBOX-TSR > TSR.LOG
DIR > NUL
TSRHOST
RA-TSR /U > UNLOAD.LOG
